[package]
name = "piet-web-example"
version = "0.0.1"
authors = ["Ryan Levick <ryan.levick@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
piet = { path = "../../../piet" }
piet-web = { path = "../.." }
wasm-bindgen = "0.2.30"
kurbo = {path = "/Users/raphl/github/kurbo"}

[dependencies.web-sys]
version = "0.3.6"
features = ["CanvasRenderingContext2d", "Window", "Document", "Element", "HtmlElement", "HtmlCanvasElement"]
