[package]
name = "piet-web-example"
version = "0.0.1"
authors = ["Ryan Levick <ryan.levick@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
piet = { path = "../../../piet" }
piet-web = { path = "../.." }
piet-test = { path = "../../../piet-test" }
wasm-bindgen = "0.2.30"
kurbo = "0.2.0"

[dependencies.web-sys]
version = "0.3.8"
features = ["CanvasRenderingContext2d", "Window", "Document", "Element", "HtmlElement", "HtmlCanvasElement"]
