[package]
name = "piet-web"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "Web canvas backend for piet 2D graphics abstraction."
license = "MIT/Apache-2.0"
edition = "2018"
keywords = ["graphics", "2d"]
categories = ["rendering::graphics-api", "wasm"]

[dependencies]
kurbo = "0.1.2"
piet = { path = "../piet" }

stdweb = "0.4.12"
