[package]
name = "piet-web"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "Web canvas backend for piet 2D graphics abstraction."
license = "MIT/Apache-2.0"
edition = "2018"
keywords = ["graphics", "2d"]
categories = ["rendering::graphics-api", "wasm"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
kurbo = {path = "/Users/raphl/github/kurbo"}
piet = { path = "../piet" }

wasm-bindgen = "0.2.30"

[dependencies.web-sys]
version = "0.3.6"
features = ["CanvasRenderingContext2d", "CanvasWindingRule", "TextMetrics"]
