[package]
name = "piet-cairo"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "Cairo backend for piet 2D graphics abstraction."
license = "MIT/Apache-2.0"
edition = "2018"
keywords = ["graphics", "2d"]
categories = ["rendering::graphics-api"]

[dependencies]
kurbo = "0.2.0"
piet = { path = "../piet" }

[dependencies.cairo-rs]
version = "0.5.0"
# We don't need glib
default-features = false

[dev-dependencies]
piet-test = { path = "../piet-test" }

[dev-dependencies.cairo-rs]
version = "0.5.0"
features = ["png"]
default-features = false
